Public Class UC_PARAMETRO_DOCUMENTO_D0M4
#Region "VARIABLES Y CONSTANTES MODULARES"

    Public VM_NOMBRE_TABLA As String
    Public VM_IN_MODO_OPERACION As Integer = 0
    Public VM_ID_BASE_DE_DATOS As Integer = 0

#End Region

#Region "FUNCIONES_FM"

    Public Function FM_SQL_LISTADO() As String
        Dim VP_PARAMETROS As String = ""
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_LI_BUSCAR, True)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, CB_LI_ZONA_UO, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, CB_LI_UNIDAD_OPERATIVA, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, CB_LI_TIEMPO_YYYY, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, CB_LI_TIEMPO_MES, False)
        Return VP_PARAMETROS
    End Function

    Public Function FM_FI_SQL(ByRef PP_NUEVO As Boolean)
        Dim VP_PARAMETROS = ""
        PP_NUEVO = True
        If TB_K_DOCUMENTO_D0M4.Text <> "" Then
            Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_K_DOCUMENTO_D0M4, False)
            PP_NUEVO = False
        Else
            Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, CB_DOCUMENTO_D0M4, False)
        End If
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_P2016_DTO_DESCUENTO_X_KG, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_DESCUENTO_CONTADO, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_DESCUENTO_CREDITO, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_P2023_PCN, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_P1003_VENTA_KG_CONTADO, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_P1004_VENTA_KG_CREDITO, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_P1012_CARTERA_CYC_INICIAL, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_P1013_CARTERA_CYC_FINAL, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_COBRANZA_HOLGURA, False)

        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_PERFIL_VENTA_CONTADO_1_LUNES, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_PERFIL_VENTA_CONTADO_2_MARTES, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_PERFIL_VENTA_CONTADO_3_MIERCOLES, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_PERFIL_VENTA_CONTADO_4_JUEVES, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_PERFIL_VENTA_CONTADO_5_VIERNES, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_PERFIL_VENTA_CONTADO_6_SABADO, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_PERFIL_VENTA_CONTADO_7_DOMINGO, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_PERFIL_VENTA_CREDITO_1_LUNES, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_PERFIL_VENTA_CREDITO_2_MARTES, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_PERFIL_VENTA_CREDITO_3_MIERCOLES, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_PERFIL_VENTA_CREDITO_4_JUEVES, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_PERFIL_VENTA_CREDITO_5_VIERNES, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_PERFIL_VENTA_CREDITO_6_SABADO, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_PERFIL_VENTA_CREDITO_7_DOMINGO, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_PERFIL_COBRANZA_1_LUNES, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_PERFIL_COBRANZA_2_MARTES, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_PERFIL_COBRANZA_3_MIERCOLES, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_PERFIL_COBRANZA_4_JUEVES, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_PERFIL_COBRANZA_5_VIERNES, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_PERFIL_COBRANZA_6_SABADO, False)
        Codigo_CTRL.PG_CO_PARAMETRO(VP_PARAMETROS, TB_PERFIL_COBRANZA_7_DOMINGO, False)
        Return VP_PARAMETROS

    End Function

    Public Function FM_DESC_SELECCIONADO(ByRef PP_LISTADO As DataGridView, ByRef PP_ROW As Integer) As String
        Dim VP_ID As String = ""
        VP_ID = Codigo_LI.FG_LI_CELL_READ(PP_LISTADO, PP_ROW, "D_DOCUMENTO_D0M4")
        Return VP_ID
    End Function

    Public Function FM_ID_SELECCIONADO(ByRef PP_LISTADO As DataGridView, ByRef PP_ROW As Integer) As String
        Dim VP_ID As String = ""
        VP_ID = Codigo_LI.FG_LI_CELL_READ(PP_LISTADO, PP_ROW, "K_DOCUMENTO_D0M4")
        Return VP_ID
    End Function

    Public Function FM_SAVE_VALIDATE(ByRef PP_MENSAJE_VALIDACION As String) As Boolean
        Dim VP_VALIDACION As Boolean

        Codigo_FI.PG_FI_FIELDS_VALIDATE(GB_FICHA, VP_VALIDACION, PP_MENSAJE_VALIDACION)

        'Codigo_CTRL.PG_TB_INTEGER_VALIDATE(PP_MENSAJE_VALIDACION, TB_O_DOCUMENTO_D0M4)


        VP_VALIDACION = (PP_MENSAJE_VALIDACION = "")

        Return VP_VALIDACION
    End Function

#End Region

#Region "SUB_PM_INIT"

    Public Sub PM_FO_SHOW(ByRef PP_NOMBRE_TABLA As String, ByVal PP_ID_BASE_DE_DATOS As String)
        VM_NOMBRE_TABLA = PP_NOMBRE_TABLA
        VM_ID_BASE_DE_DATOS = PP_ID_BASE_DE_DATOS
        'Me.Show()
    End Sub

    Public Sub PM_CB_INIT()
        Codigo_FI.PG_FI_CONTROL_DATA_SETUP(VM_ID_BASE_DE_DATOS, Me)
        Codigo_CB.PG_CB_LOAD_X_ORDEN(VM_ID_BASE_DE_DATOS,Me, CB_LI_TIEMPO_MES, "MES")
        Codigo_CB.PG_CB_LOAD_X_ORDEN(VM_ID_BASE_DE_DATOS,Me, CB_LI_ZONA_UO, "ZONA_UO")
        Codigo_CB.PG_CB_LOAD_X_ORDEN(VM_ID_BASE_DE_DATOS,Me, CB_LI_TIEMPO_YYYY, "TIEMPO_YYYY")
        Codigo_CB.PG_CB_LOAD_X_ORDEN(VM_ID_BASE_DE_DATOS,Me, CB_LI_UNIDAD_OPERATIVA, "UNIDAD_OPERATIVA")
        Codigo_CB.PG_CB_LOAD_X_ORDEN(VM_ID_BASE_DE_DATOS,Me, CB_USUARIO_ALTA, "USUARIO")
        Codigo_CB.PG_CB_LOAD_X_ORDEN(VM_ID_BASE_DE_DATOS,Me, CB_USUARIO_CAMBIO, "USUARIO")
        Codigo_CB.PG_CB_LOAD_X_ORDEN(VM_ID_BASE_DE_DATOS,Me, CB_DOCUMENTO_D0M4, "")

    End Sub

    Public Sub PM_LI_INIT()
        PM_LI_FORMAT(LI_LISTADO)
    End Sub

    Private Sub PM_FO_INIT(ByRef PP_FORMA As Object)
        Me.PM_FO_SHOW("PARAMETRO_DOCUMENTO_D0M4", "6")
        Codigo_FRM.PG_FRM_INIT(VM_ID_BASE_DE_DATOS, PP_FORMA)
    End Sub

#End Region

#Region "SUBS_PM"

    ''' <summary>
    ''' 'FUNCION QUE CARGARA LA PARTE DE LA FICHA
    ''' </summary>
    Public Sub PM_FI_LOAD(ByVal PP_ID As String)
        Codigo_FI.FG_FI_LOAD_X_ID(VM_ID_BASE_DE_DATOS,  Me, PP_ID)
        'CB_UNIDAD_OPERATIVA.Select()
    End Sub

    Public Sub PM_FI_CARGAR(ByVal PP_ROW As DataRow)

        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_K_DOCUMENTO_D0M4, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_P2016_DTO_DESCUENTO_X_KG, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_DESCUENTO_CREDITO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_DESCUENTO_CONTADO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_P2023_PCN, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_P1003_VENTA_KG_CONTADO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_P1004_VENTA_KG_CREDITO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_P2023_PCN, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_P1013_CARTERA_CYC_FINAL, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_P1012_CARTERA_CYC_INICIAL, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_COBRANZA_HOLGURA, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CONTADO_1_LUNES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CONTADO_2_MARTES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CONTADO_3_MIERCOLES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CONTADO_4_JUEVES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CONTADO_5_VIERNES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CONTADO_6_SABADO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CONTADO_7_DOMINGO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CREDITO_1_LUNES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CREDITO_2_MARTES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CREDITO_3_MIERCOLES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CREDITO_4_JUEVES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CREDITO_5_VIERNES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CREDITO_6_SABADO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CREDITO_7_DOMINGO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_COBRANZA_1_LUNES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_COBRANZA_2_MARTES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_COBRANZA_3_MIERCOLES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_COBRANZA_4_JUEVES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_COBRANZA_5_VIERNES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_COBRANZA_6_SABADO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_COBRANZA_7_DOMINGO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", CB_USUARIO_ALTA, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", CB_USUARIO_CAMBIO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_F_ALTA, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_F_CAMBIO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", CB_DOCUMENTO_D0M4, PP_ROW)
        Codigo_FI.PG_FI_CONTROL_DATA_LOAD(Me, PP_ROW)
        FO_WIZARD.PP_K_PARAMETRO_DOCUMENTO_D0M4 = TB_K_DOCUMENTO_D0M4.Text

    End Sub

    Public Sub PM_FI_CARGAR_PERFIL(ByVal PP_ROW As DataRow)

        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_P2016_DTO_DESCUENTO_X_KG, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_DESCUENTO_CREDITO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_DESCUENTO_CONTADO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_P2023_PCN, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_P1003_VENTA_KG_CONTADO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_P1004_VENTA_KG_CREDITO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_P2023_PCN, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_P1013_CARTERA_CYC_FINAL, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_P1012_CARTERA_CYC_INICIAL, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_COBRANZA_HOLGURA, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CONTADO_1_LUNES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CONTADO_2_MARTES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CONTADO_3_MIERCOLES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CONTADO_4_JUEVES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CONTADO_5_VIERNES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CONTADO_6_SABADO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CONTADO_7_DOMINGO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CREDITO_1_LUNES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CREDITO_2_MARTES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CREDITO_3_MIERCOLES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CREDITO_4_JUEVES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CREDITO_5_VIERNES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CREDITO_6_SABADO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_VENTA_CREDITO_7_DOMINGO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_COBRANZA_1_LUNES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_COBRANZA_2_MARTES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_COBRANZA_3_MIERCOLES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_COBRANZA_4_JUEVES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_COBRANZA_5_VIERNES, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_COBRANZA_6_SABADO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_PERFIL_COBRANZA_7_DOMINGO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", CB_USUARIO_ALTA, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", CB_USUARIO_CAMBIO, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_F_ALTA, PP_ROW)
        Codigo_CTRL.PG_CO_DATA_LOAD("", TB_F_CAMBIO, PP_ROW)

    End Sub

    Private Sub PM_LI_FORMAT(ByRef PP_LI_LISTADO As DataGridView)
        Codigo_LI.PG_LI_FORMAT_SETUP(PP_LI_LISTADO, 8, 16)
        'PARAMETROS: NOMBRE_DATAGRIDVIEW, NOMBRE_COLUMNA, HEADER_TEXT, TIPO_DATO, 
        '            ANCHO_CELDA, ALINEACION, SOLO_LECTURA, Visible, FROZEN, FORMAT
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "K_DOCUMENTO_D0M4", "ID", GetType(Integer), 80, 1, 1, 1, 1, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "D_DOCUMENTO_D0M4", "DESCRIPCION", GetType(String), 170, 1, 1, 1, 1, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "P2016_DTO_DESCUENTO_X_KG", "DESCUENTO X KG", GetType(Decimal), 100, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "DESCUENTO_CONTADO", "DESCUENTO DE CONTADO", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "DESCUENTO_CREDITO", "DESCUENTO DE CREDITO", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "P2023_PCN", "PCN", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "P1003_VENTA_KG_CONTADO", "VENTA KG CONTADO", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "P1004_VENTA_KG_CREDITO", "VENTA KG CREDITO", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "P1012_CARTERA_CYC_INICIAL", "CARTERA CYC INICIAL", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "P1013_CARTERA_CYC_FINAL", "CARTERA CYC FINAL", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "COBRANZA_HOLGURA", "COBRANZA HOLGURA", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "PERFIL_VENTA_CONTADO_1_LUNES", "VENTA CONTADO LUNES", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "PERFIL_VENTA_CONTADO_2_MARTES", "VENTA CONTADO MARTES", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "PERFIL_VENTA_CONTADO_3_MIERCOLES", "VENTA CONTADO MIERCOLES", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "PERFIL_VENTA_CONTADO_4_JUEVES", "VENTA CONTADO JUEVES", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "PERFIL_VENTA_CONTADO_5_VIERNES", "VENTA CONTADO VIERNES", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "PERFIL_VENTA_CONTADO_6_SABADO", "VENTA CONTADO SABADO", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "PERFIL_VENTA_CONTADO_7_DOMINGO", "VENTA CONTADO DOMINGO", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "PERFIL_VENTA_CREDITO_1_LUNES", "VENTA CREDITO LUNES", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "PERFIL_VENTA_CREDITO_2_MARTES", "VENTA CREDITO MARTES", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "PERFIL_VENTA_CREDITO_3_MIERCOLES", "VENTA CREDITO MIERCOLES", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "PERFIL_VENTA_CREDITO_4_JUEVES", "VENTA CREDITO JUEVES", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "PERFIL_VENTA_CREDITO_5_VIERNES", "VENTA CREDITO VIERNES", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "PERFIL_VENTA_CREDITO_6_SABADO", "VENTA CREDITO SABADO", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "PERFIL_VENTA_CREDITO_7_DOMINGO", "VENTA CREDITO DOMINGO", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "PERFIL_COBRANZA_1_LUNES", "COBRANZA LUNES", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "PERFIL_COBRANZA_2_MARTES", "COBRANZA MARTES", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "PERFIL_COBRANZA_3_MIERCOLES", "COBRANZA MIERCOLES", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "PERFIL_COBRANZA_4_JUEVES", "COBRANZA JUEVES", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "PERFIL_COBRANZA_5_VIERNES", "COBRANZA VIERNES", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "PERFIL_COBRANZA_6_SABADO", "COBRANZA SABADO", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_LI.PG_LI_COLUMN_ADD(PP_LI_LISTADO, "PERFIL_COBRANZA_7_DOMINGO", "COBRANZA DOMINGO", GetType(Decimal), 89, 1, 1, 1, 0, 0)
        Codigo_FRM.PG_FRM_LI_FORMAT_CONTROL_LOAD(PP_LI_LISTADO, 100, 2, 0, 0, 0, 0)
    End Sub

    Public Sub PM_LI_ROW_WRITE(ByRef PP_LISTADO As DataGridView, ByRef PP_ROW_DATA As DataRow)
        Dim VP_COLUMNA As Integer = 0
        Dim VP_ROW As Integer
        VP_ROW = Codigo_LI.FG_LI_MAX_ROW(PP_LISTADO)
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "K_DOCUMENTO_D0M4")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "D_DOCUMENTO_D0M4")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "P2016_DTO_DESCUENTO_X_KG")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "DESCUENTO_CONTADO")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "DESCUENTO_CREDITO")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "P2023_PCN")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "P1003_VENTA_KG_CONTADO")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "P1004_VENTA_KG_CREDITO")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "P1012_CARTERA_CYC_INICIAL")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "P1013_CARTERA_CYC_FINAL")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "COBRANZA_HOLGURA")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "PERFIL_VENTA_CONTADO_1_LUNES")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "PERFIL_VENTA_CONTADO_2_MARTES")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "PERFIL_VENTA_CONTADO_3_MIERCOLES")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "PERFIL_VENTA_CONTADO_4_JUEVES")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "PERFIL_VENTA_CONTADO_5_VIERNES")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "PERFIL_VENTA_CONTADO_6_SABADO")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "PERFIL_VENTA_CONTADO_7_DOMINGO")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "PERFIL_VENTA_CREDITO_1_LUNES")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "PERFIL_VENTA_CREDITO_2_MARTES")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "PERFIL_VENTA_CREDITO_3_MIERCOLES")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "PERFIL_VENTA_CREDITO_4_JUEVES")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "PERFIL_VENTA_CREDITO_5_VIERNES")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "PERFIL_VENTA_CREDITO_6_SABADO")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "PERFIL_VENTA_CREDITO_7_DOMINGO")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "PERFIL_COBRANZA_1_LUNES")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "PERFIL_COBRANZA_2_MARTES")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "PERFIL_COBRANZA_3_MIERCOLES")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "PERFIL_COBRANZA_4_JUEVES")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "PERFIL_COBRANZA_5_VIERNES")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "PERFIL_COBRANZA_6_SABADO")
        Codigo_LI.PG_LI_CELL_WRITE_SECUENCIAL(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA, "PERFIL_COBRANZA_7_DOMINGO")
        Codigo_FRM.PG_FRM_LI_DATA_CONTROL_LOAD(PP_LISTADO, VP_ROW, VP_COLUMNA, PP_ROW_DATA)
        Codigo_LI.PG_LI_ROW_EDIT(PP_LISTADO, VP_ROW, False)
    End Sub

    Public Sub PM_BT_BUSCAR_CLICK(ByRef PP_FORMA As Object, ByVal PP_LISTADO As DataGridView)
        Codigo_ABC.PG_BT_BUSCAR_CLICK(VM_ID_BASE_DE_DATOS, PP_FORMA, PP_LISTADO)
    End Sub

    Private Sub PM_BT_AGREGAR_CLICK(ByRef PP_FORMA As Object)
        CB_DOCUMENTO_D0M4.Enabled = True
        Codigo_ABC.PG_BT_AGREGAR_CLICK(PP_FORMA)
    End Sub

    Private Sub PM_BT_CANCELAR_CLICK(ByRef PP_FORMA As Object)
        CB_DOCUMENTO_D0M4.Enabled = False
        Codigo_ABC.PG_BT_CANCELAR_CLICK(PP_FORMA)
    End Sub

    Private Sub PM_BT_SALIR_CLICK(ByRef PP_FORMA As Object)
        Codigo_ABC.PG_BT_SALIR_CLICK(PP_FORMA)
    End Sub

    Private Sub PM_BT_EDITAR_CLICK(ByRef PP_FORMA As Object, ByVal PP_LISTADO As DataGridView)
        Codigo_ABC.PG_BT_EDITAR_CLICK(PP_FORMA, PP_LISTADO)
    End Sub

    Public Sub PM_BT_GUARDAR_CLICK(ByRef PP_FORMA As Object, ByRef PP_LISTADO As DataGridView)

         Codigo_ABC.PG_BT_GUARDAR_CLICK(VM_ID_BASE_DE_DATOS,PP_FORMA, PP_LISTADO)
        FO_DATA_N1_X_DI_D0M4_FLUP.PM_FO_SHOW("DATA_N1_X_DI_D0M4", 6) 'WE INVOKE DATA_N1_X_DI FORM AFTER WE UPDATE OR INSERT PARAMETERS CODEMAJIC
    End Sub

    Public Sub PM_BT_ELIMINAR_CLICK(ByRef PP_FORMA As Object, ByRef PP_LISTADO As DataGridView)
        Codigo_ABC.PG_BT_ELIMINAR_CLICK(VM_ID_BASE_DE_DATOS,PP_FORMA, PP_LISTADO)
    End Sub

    Private Sub PM_TI_TICK(ByRef PP_LABEL As Label)
        Codigo_FRM.PG_TI_TICK(PP_LABEL)
    End Sub

    Private Sub PM_BT_LISTADO_CLICK(ByRef PP_FORMA As Object)
        Codigo_ABC.PG_BT_LISTADO_CLICK(PP_FORMA)
    End Sub

    Private Sub PM_BT_EXPORTAR_EXCEL_CLICK(ByRef PP_LISTADO As DataGridView)
        Codigo_ABC.PG_BT_EXPORTAR_EXCEL_CLICK(PP_LISTADO)
    End Sub

    Public Sub PM_LI_SAVE(ByRef PP_FORMA As Object, ByRef PP_LISTADO As DataGridView)
        PM_BT_BUSCAR_CLICK(PP_FORMA, PP_LISTADO)
    End Sub

    Public Sub PM_MODO_AUXILIAR()

    End Sub

#End Region

#Region "EVENTOS"

    Private Sub BT_AGREGAR_Click(sender As Object, e As EventArgs) Handles BT_AGREGAR.Click
        PM_BT_AGREGAR_CLICK(Me)
    End Sub

    Private Sub BT_BUSCAR_Click(sender As Object, e As EventArgs) Handles BT_LI_BUSCAR.Click
        PM_BT_BUSCAR_CLICK(Me, LI_LISTADO)
    End Sub

    Private Sub Catalogo_T1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        PM_FO_INIT(Me)
    End Sub

    Private Sub BT_CANCELAR_Click(sender As Object, e As EventArgs) Handles BT_CANCELAR.Click
        PM_BT_CANCELAR_CLICK(Me)
    End Sub

    Private Sub BT_SALIR_Click(sender As Object, e As EventArgs)
        PM_BT_SALIR_CLICK(Me)
    End Sub
    Private Sub BT_GUARDAR_Click(sender As Object, e As EventArgs) Handles BT_GUARDAR.Click
        PM_BT_GUARDAR_CLICK(Me, LI_LISTADO)
    End Sub

    Private Sub BT_EDITAR_Click(sender As Object, e As EventArgs) Handles BT_EDITAR.Click
        PM_BT_EDITAR_CLICK(Me, LI_LISTADO)
    End Sub

    Private Sub BT_ELIMINAR_Click(sender As Object, e As EventArgs) Handles BT_ELIMINAR.Click
        PM_BT_ELIMINAR_CLICK(Me, LI_LISTADO)
    End Sub

    Private Sub LI_LISTADO_DoubleClick(sender As Object, e As EventArgs) Handles LI_LISTADO.DoubleClick
        Codigo_LI.PG_LI_DOUBLE_CLICK(Me, LI_LISTADO)
    End Sub

    Private Sub TI_RELOJ_Tick(sender As Object, e As EventArgs) Handles TI_RELOJ.Tick
        PM_TI_TICK(LB_RELOJ)
    End Sub

    Private Sub BT_LISTADO_Click(sender As Object, e As EventArgs) Handles BT_LISTADO.Click
        PM_BT_LISTADO_CLICK(Me)
    End Sub

    Private Sub BT_EXPORTAR_EXCEL_Click(sender As Object, e As EventArgs) Handles BT_EXPORTAR_EXCEL.Click
        PM_BT_EXPORTAR_EXCEL_CLICK(LI_LISTADO)
    End Sub

    Private Sub UC_PARAMETRO_DOCUMENTO_D0M4_VisibleChanged(sender As Object, e As EventArgs) Handles MyBase.VisibleChanged
        If Me.Visible Then
            If FO_WIZARD.PP_K_PARAMETRO_DOCUMENTO_D0M4 = 0 And FO_WIZARD.PP_UNIDAD_OPERATIVA > 0 Then
                VM_IN_MODO_OPERACION = Modo_Operacion.Edición
                Codigo_FRM.PG_FRM_CONFIG(Me)
                'Codigo_CB.PG_CB_LOAD_X_ORDEN(VM_ID_BASE_DE_DATOS,Me, CB_PERFIL, "PG_LD_PARAMETRO_SUCURSAL_D0M4", FO_WIZARD.PP_UNIDAD_OPERATIVA)
                GB_OPCION.Visible = True
                GB_OPCION.Enabled = True
            End If
            If FO_WIZARD.PP_K_DOCUMENTO_D0M4 > 0 Then
                VM_IN_MODO_OPERACION = Modo_Operacion.Edición
                Codigo_FRM.PG_FRM_CONFIG(Me)
                Codigo_CB.PG_CB_VALUE_LOAD(CB_DOCUMENTO_D0M4, FO_WIZARD.PP_K_DOCUMENTO_D0M4)
                GB_OPCION.Visible = True
                GB_OPCION.Enabled = True
            End If

        End If
    End Sub

    Private Sub GB_FICHA_VisibleChanged(sender As Object, e As EventArgs) Handles GB_FICHA.VisibleChanged
        If GB_FICHA.Visible Then
            GB_OPCION.Visible = True
        Else
            GB_OPCION.Visible = False
        End If
    End Sub

    Private Sub Button1_Click(sender As Object, e As EventArgs)
        ' [PG_SK_PARAMETRO_SUCURSAL_D0M4]
    End Sub

    Private Sub BT_CARGAR_PERFIL_Click(sender As Object, e As EventArgs) Handles BT_CARGAR_PERFIL.Click
        If CB_PERFIL.SelectedIndex > -1 Then
            Dim VP_PARAMETROS As String = Codigo_CB.FG_CB_ITEM_VALUE(CB_PERFIL)
            Codigo_CON.PG_SQL_PARAMETROS_CONTROL(VP_PARAMETROS)
            Dim VP_DATA_PERFIL As DataTable = Codigo_CON.FG_SP_EXECUTE_DATATABLE(VM_ID_BASE_DE_DATOS, "PG_SK_PARAMETRO_SUCURSAL_D0M4", VP_PARAMETROS)
            If VP_DATA_PERFIL.Rows IsNot Nothing Then
                If VP_DATA_PERFIL.Rows.Count > 0 Then
                    PM_FI_CARGAR_PERFIL(VP_DATA_PERFIL.Rows(0))
                End If
            End If
        End If

    End Sub

#End Region
End Class
